### ISSUE TITLE
Rails agnostic

### ISSUE THREAD

**Issue by cpursley** [vprokopchuk256/mv-core#4]
Neat project. Would it be possible to remove the Rails dependency requirements so we can use mv in other Ruby projects that use activerecord?

**Comment by vprokopchuk256** [comment]
@cpursley  - sorry for delay with the answer. Is busy on other project right now. Never though about it. Project was created for personal use initially and published with time. I will think about it for sure. Also would appreciate any help if you have time for that.

**Comment by cpursley** [comment]
I've moved on to using sequel for now due to it's more powerful migration tool toolset.
