### ISSUE TITLE
enforce_migration_validations in any model prevents db:schema:load from working

### ISSUE THREAD

**Issue by singpolyma** [vprokopchuk256/mv-core#7]
I complains about not finding the validations table... well of course, I'm running the script that creates it! Right now I have to comment it out in every model for each new person I set up.

**Comment by vprokopchuk256** [comment]
@singpolyma  - ok. Got it. I will look into it.

**Comment by vprokopchuk256** [comment]
@singpolyma  - should be fixed in all adapters with version >= 2.2.5. Verify it, pls.

**Comment by singpolyma** [comment]
seems to be working.  thanks!
